PATH_RECV_CLIENT=/home/penitent/project/RFTU/client/client_recv.txt
PATH_SEND_CLIENT=/home/penitent/project/RFTU/client/client_send.txt
PATH_RECV_SERVER=/home/penitent/project/RFTU/server/server_recv.txt
PATH_SEND_SERVER=/home/penitent/project/RFTU/server/server_send.txt